[package]
name = "silversnail-native"
version = "0.1.0"
authors = ["nasso"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.3"
futures = "0.3.5"
wgpu = "0.5.0"
